apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod-v5
  labels:                  # You'll use labels A LOT w/ kube
    app: hello-world       # They are useful for organizing and identifying attributes of an object
spec:
  containers:              # This spec has multiple containers, how fancy!
  - name: hello-world-sh
    image: busybox
    command: ['sh', '-c', 'echo Hello World v5 && sleep 3600']
